gatewayapps/grayskull

.dockerignore, config/default.js, docker-compose.yml, dockerfile, examples/testClient/config.js, examples/testClient/package-lock.json, examples/testClient/package.json, package-lock.json, package.json, src/tsconfig-paths-bootstrapper.ts, tsconfig.json
=> MySql migration and Docker build support

cradle/cradle.yml, cradle/emitters/cradle.apollo-emitter.js, cradle/emitters/cradle.sequelize-attributes-emitter.js, cradle/emitters/cradle.sequelize-instance-emitter.js, cradle/specs/PhoneNumber.yml, cradle/specs/UserAccount.yml, src/api/services/PhoneNumberService.ts, src/data/context.ts, src/data/graphql/PhoneNumber/typedefs.graphql, src/data/graphql/UserAccount/typedefs.graphql, src/data/models/IPhoneNumber.ts, src/data/models/IUserAccount.ts, src/data/models/PhoneNumber.ts, src/data/models/UserAccount.ts, src/data/repositories/PhoneNumberRepository.ts, src/interfaces/graphql/IPhoneNumber.ts, src/interfaces/graphql/IUserAccount.ts
Completes the first to-do for #84
=> added phoneNumber model

.vscode/settings.json, package.json, src/api/controllers/loginController.ts, src/api/services/AuthenticationService.ts, src/api/services/TokenService.ts, src/api/services/UserAccountService.ts, src/data/graphql/UserAccount/resolvers.ts, tslint.json
=> Hybrid flow

package.json, src/RealmInstance.ts, src/api/services/MailService.ts
=> Fix SMTP Connection missing credentials

src/middleware/authentication.ts
=> Update user last active

public/components/LoginForm.js
=> Fix enter key on login MFA screen sending backup code

public/components/ChangePasswordForm.js
=> Redirect to login after resetting password

public/components/EditableUserProfile.tsx
=> Changed placeholder for display name to Enter Display Name.

activities/sendEmailVerification.ts, activities/sendResetPasswordEmail.ts, communication/graphql/UserAccount/validateResetPasswordTokenResolver.ts, communication/graphql/UserAccount/verifyEmailAddressResolver.ts
=> uri encode email addresses in activation/reset password links

activities/tokens/getTokensFromMultifactorTokenActivity.ts, package.json, pages/authorize.tsx
Fixing a bug with the mfa token verification
=> Added await to mfa token check for sdk

presentation/components/EditableUserProfile.tsx
=> Fix bug with user role not updating in UI

activities/admin/createUserAccountActivity.spec.ts, activities/listUserAccountEmailAddressesActivity.ts, presentation/components/EditableUserProfile.tsx
=> Added password to create user mutation

activities/activateAccountActivity.spec.ts
=> Added tests for activateAccountActivity

activities/authentication/changePasswordWithOldPasswordActivity.ts, activities/authentication/changePasswordWithTokenActivity.ts, activities/setPrimaryEmailAddressForUserActivity.ts, operations/services/mail/sendEmailTemplate.ts, operations/services/mail/sendEmailUsingNodemailer.ts, operations/services/mail/templates/passwordEmailChangeTemplate.html.handlebars, operations/services/mail/templates/passwordEmailChangeTemplate.text.handlebars
- resolves #164 
- Sends email after changing account password, or setting new primary email
- Set primary email address to different email from personal info menu
- Change password from security menu
"this" was the account name
=> Added emails for account password or primary email changed

pages/logout.tsx
Relies on #315 #312 to be merged to be able to fully work.
- resolves #317 
- Added a logout flow to allow the RP to redirect to the OP (grayskull) with the `redirect_uri` in the query params. 
-
=> RP to OP logout flow + redirect

operations/logic/ensureAdministrator.spec.ts
- resolves #326 
- Added unit test
- yarn test operations/logic/ensureAdministrator.spec.ts
=> Created test for ensure administrator.

package.json, pages/_document.tsx
=> chore: Refactored document.js to typescript

operations/logic/isEmailAddressDomainAllowed.spec.ts, yarn.lock
- resolves #329 
- Added tests for `isEmailAddressDomainAllowed` in multiple variations
- `yarn test-operations`
=> Adding tests for logic/isEmailAddressDomainAllowed

presentation/components/LoginForm/Credentials.tsx, presentation/components/LoginForm/index.tsx, presentation/components/MutationButton.tsx
=> autosubmit token when filled

pages/login.js, presentation/components/ApplicationInitializer.tsx
- resolves #389 
- Refactor the redirection logic
-Should redirect correctly
=> Fix incorrect redirect
